export const africanCountries: { value: string; label: string }[] = [
	{ value: "algeria", label: "Algeria" },
	{ value: "angola", label: "Angola" },
	{ value: "benin", label: "Benin" },
	{ value: "botswana", label: "Botswana" },
	{ value: "burkina-faso", label: "Burkina Faso" },
	{ value: "burundi", label: "Burundi" },
	{ value: "cameroon", label: "Cameroon" },
	{ value: "cape-verde", label: "Cape Verde" },
	{ value: "central-african-republic", label: "Central African Republic" },
	{ value: "chad", label: "Chad" },
	{ value: "comoros", label: "Comoros" },
	{ value: "congo-brazzaville", label: "Congo (Brazzaville)" },
	{ value: "congo-kinshasa", label: "Congo (Kinshasa)" },
	{ value: "djibouti", label: "Djibouti" },
	{ value: "egypt", label: "Egypt" },
	{ value: "equatorial-guinea", label: "Equatorial Guinea" },
	{ value: "eritrea", label: "Eritrea" },
	{ value: "eswatini", label: "Eswatini" },
	{ value: "ethiopia", label: "Ethiopia" },
	{ value: "gabon", label: "Gabon" },
	{ value: "gambia", label: "Gambia" },
	{ value: "ghana", label: "Ghana" },
	{ value: "guinea", label: "Guinea" },
	{ value: "guinea-bissau", label: "Guinea-Bissau" },
	{ value: "ivory-coast", label: "Ivory Coast" },
	{ value: "kenya", label: "Kenya" },
	{ value: "lesotho", label: "Lesotho" },
	{ value: "liberia", label: "Liberia" },
	{ value: "libya", label: "Libya" },
	{ value: "madagascar", label: "Madagascar" },
	{ value: "malawi", label: "Malawi" },
	{ value: "mali", label: "Mali" },
	{ value: "mauritania", label: "Mauritania" },
	{ value: "mauritius", label: "Mauritius" },
	{ value: "morocco", label: "Morocco" },
	{ value: "mozambique", label: "Mozambique" },
	{ value: "namibia", label: "Namibia" },
	{ value: "niger", label: "Niger" },
	{ value: "nigeria", label: "Nigeria" },
	{ value: "rwanda", label: "Rwanda" },
	{ value: "sao-tome-and-principe", label: "Sao Tome and Principe" },
	{ value: "senegal", label: "Senegal" },
	{ value: "seychelles", label: "Seychelles" },
	{ value: "sierra-leone", label: "Sierra Leone" },
	{ value: "somalia", label: "Somalia" },
	{ value: "south-africa", label: "South Africa" },
	{ value: "south-sudan", label: "South Sudan" },
	{ value: "sudan", label: "Sudan" },
	{ value: "tanzania", label: "Tanzania" },
	{ value: "togo", label: "Togo" },
	{ value: "tunisia", label: "Tunisia" },
	{ value: "uganda", label: "Uganda" },
	{ value: "zambia", label: "Zambia" },
	{ value: "zimbabwe", label: "Zimbabwe" },
];
